stages:
  - deploy_stage

.base-rules:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never
    - if: $CI_COMMIT_TAG
      when: never

deploy:
  stage: deploy_stage
  extends: .base-rules
  script:
    - npm i
    - npm run build
    - 'pm2 start ecosystem.config.js'
  tags:
    - local_runner
