import '@/assets/styles/app.scss'

import type { Metadata } from 'next'

import { LayoutHeader } from '@/components/Layout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body>
        <div className={'page'}>
          {/* <LayoutHeader /> */}
          {/* <LayoutMenu /> */}
          {children}
          {/* <LayoutFooter /> */}
          {/* <SharedModals /> */}
        </div>
      </body>
    </html>
  )
}
